### ISSUE TITLE
home/gzx/AttentionalPoolingAction/src/custom_ops/pose_to_heatmap.so: cannot open shared object file: No such file or directory‘

### ISSUE THREAD

**Issue by zhangxgu** [rohitgirdhar/AttentionalPoolingAction#1]
When I was going to run  **python eval.py --cfg ../experiments/001_MPII_ResNet_pretrained.yaml** and I found that this file was not exist.  So where can I find this .so file? Thank you !
‘’‘
Traceback (most recent call last):
  File "eval.py", line 20, in <module>
    from datasets import dataset_factory
  File "/home/gzx/AttentionalPoolingAction/src/datasets/dataset_factory.py", line 8, in <module>
    from datasets import hmdb51
  File "/home/gzx/AttentionalPoolingAction/src/datasets/hmdb51.py", line 8, in <module>
    from datasets.video_data_utils import gen_dataset
  File "/home/gzx/AttentionalPoolingAction/src/datasets/video_data_utils.py", line 18, in <module>
    from custom_ops.custom_ops_factory import read_json_pose, read_sparse_label
  File "/home/gzx/AttentionalPoolingAction/src/custom_ops/custom_ops_factory.py", line 12, in <module>
    os.path.join(ROOT_PATH, 'pose_to_heatmap.so')).pose_to_heatmap
  File "/home/gzx/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/gzx/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/gzx/AttentionalPoolingAction/src/custom_ops/pose_to_heatmap.so: cannot open shared object file: No such file or directory‘
’’‘’’

**Comment by xiaolata233** [comment]
I got the same problem
cannot find AttentionalPoolingAction/src/custom_ops/pose_to_heatmap.so
Have you solved it?

**Comment by rohitgirdhar** [comment]
You need to run `make` in the `src/custom_ops` directory to compile some custom ops required for loading data. I've also updated the README to reflect this.
