### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by lilyabc** [rohitgirdhar/AttentionalPoolingAction#28]
When evaluating  
```
python eval.py --cfg ../experiments/001_MPII_ResNet_pretrained.yaml
```
It outputs
```
INFO:tensorflow:Restoring parameters from pretrained_models/mpii_baseline/model.ckpt-12000
  0%|                                               | 0/6988 [00:00<?, ?it/s]Exception KeyError: KeyError(<weakref at 0x7ff7ad282f70; to 'tqdm' at 0x7ff7ad2e1f10>,) in <bound method tqdm.__del__ of   0%|                                               | 0/6988 [00:00<?, ?it/s]> ignored
Traceback (most recent call last):
  File "eval.py", line 335, in <module>
    main()
  File "eval.py", line 267, in main
    all_labels = np.concatenate(all_labels)
ValueError: need at least one array to concatenate
```
Something is wrong with https://github.com/rohitgirdhar/AttentionalPoolingAction/blob/adb3f01744085f6628ff0d68f29dffc979853765/src/eval.py#L266
and
https://github.com/rohitgirdhar/AttentionalPoolingAction/blob/adb3f01744085f6628ff0d68f29dffc979853765/src/eval.py#L303
Anyone knows this problem? Thanks.

**Comment by dbaeka** [comment]
You need to check if your tf_records were generated and placed in the right directory @lilyabc
