### ISSUE TITLE
 undefined symbol: _ZN2cv3Mat10deallocateEv

### ISSUE THREAD

**Issue by LiliMeng** [rohitgirdhar/AttentionalPoolingAction#5]
Thanks a lot for sharing the code!

When run $python eval.py --cfg ../experiments/001_MPII_ResNet_pretrained.yaml

It has the following error. Any suggestions?
Thanks a lot!

Traceback (most recent call last):
  File "eval.py", line 21, in <module>
    from datasets import dataset_factory
  File "/media/lci/storage/AttentionalPoolingAction/src/datasets/dataset_factory.py", line 8, in <module>
    from datasets import hmdb51
  File "/media/lci/storage/AttentionalPoolingAction/src/datasets/hmdb51.py", line 8, in <module>
    from datasets.video_data_utils import gen_dataset
  File "/media/lci/storage/AttentionalPoolingAction/src/datasets/video_data_utils.py", line 18, in <module>
    from custom_ops.custom_ops_factory import read_json_pose, read_sparse_label
  File "/media/lci/storage/AttentionalPoolingAction/src/custom_ops/custom_ops_factory.py", line 12, in <module>
    os.path.join(ROOT_PATH, 'pose_to_heatmap.so')).pose_to_heatmap
  File "/home/lci/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: /media/lci/storage/AttentionalPoolingAction/src/custom_ops/pose_to_heatmap.so: undefined symbol: _ZN2cv3Mat10deallocateEv

**Comment by rohitgirdhar** [comment]
Thanks for your interest. You could try some suggestions in #2.

**Comment by LiliMeng** [comment]
Thanks! Finally figured it out, the Makefile shall be the following for Ubuntu 64bit machine (test on Ubuntu16.04): 

BOOST_LIB_DIR :=  /usr/lib/x86_64-linux-gnu
#BOOST_LIB_DIR := $(BOOST_DIR)/lib
BOOST_INC_DIR := $/usr/include/
OPENCV_LIB_DIR :=/home/candice/Downloads/OpenCV/build/lib
TF_INC := $(shell python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
LDFLAGS := -Wl,--no-as-needed,-rpath,$(BOOST_LIB_DIR) -D_GLIBCXX_USE_CXX11_ABI=0 # this ensures it will look in the correct BOOST directory for libs (not the system path)

all: pose_to_heatmap.so zero_out_channels.so render_pose.so render_objects.so
